kind: Secret
apiVersion: v1
metadata:
  namespace: taco-cloud
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "secret/data/vplugin/supersecret"
type: Opaque
stringData:
  username: <username>
  password: <password>
